CREATE TABLE `groups` ( `id` INT NOT NULL AUTO_INCREMENT , `name` VARCHAR(255) NOT NULL , `description` VARCHAR(300) NULL , `isPrivate` BOOLEAN NOT NULL DEFAULT TRUE , `user_id` INT NOT NULL , `created_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP , `updated_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP , `lang` VARCHAR(2) NOT NULL DEFAULT 'en' , PRIMARY KEY (`id`)) ENGINE = InnoDB;


CREATE TABLE `groups_users` ( `group_id` INT NOT NULL , `user_id` INT NOT NULL , `type` VARCHAR(255) NOT NULL , `created_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ) ENGINE = InnoDB;


ALTER TABLE `groups_users` ADD `id` INT NOT NULL AUTO_INCREMENT AFTER `group_id`, ADD PRIMARY KEY (`id`);

ALTER TABLE `groups_users` ADD `inviter_id` INT NOT NULL DEFAULT '0' AFTER `user_id`;
